global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 5s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "physical_host"
    static_configs:
      - targets: ["172.17.0.1:9273"]
        labels:
          alias: "Host Machine"

  - job_name: "virtual_hosts"
    static_configs:
      - targets: ["device_1:9273"]
        labels:
          alias: "Ubuntu 1"
      - targets: ["device_2:9273"]
        labels:
          alias: "Ubuntu 2"
      - targets: ["device_3:9273"]
        labels:
          alias: "Ubuntu 3"
      - targets: ["device_4:9273"]
        labels:
          alias: "Alpine 1"
      - targets: ["device_5:9273"]
        labels:
          alias: "Alpine 2"