global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 4s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  # - job_name: "prometheus"
  #   static_configs:
  #     - targets:
  #         - "prometheus:9090"

  - job_name: "physical_host"
    static_configs:
      - targets: ["host.docker.internal:9273"]
        labels:
          alias: "Host Machine"

  # - job_name: "host_docker_metrics"
  #   static_configs:
  #     - targets: ["host.docker.internal:9273"]
  #       labels:
  #         alias: "Host Docker Metrics"
  #   metric_relabel_configs:
  #     # Only keep Docker metrics
  #     - source_labels: [__name__]
  #       regex: 'docker_.*'
  #       action: keep

  - job_name: "virtual_hosts"
    static_configs:
      - targets: ["device_1:9273"]
        labels:
          alias: "Ubuntu 1"
      - targets: ["device_2:9273"]
        labels:
          alias: "Ubuntu 2"
      - targets: ["device_3:9273"]
        labels:
          alias: "Ubuntu 3"
      - targets: ["device_4:9273"]
        labels:
          alias: "Alpine 1"
      - targets: ["device_5:9273"]
        labels:
          alias: "Alpine 2"