services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - devices_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # command:
    #   - "--config.file=/etc/prometheus/prometheus.yml"
    #   - "--web.enable-lifecycle"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - devices_network
    volumes:
      - grafana_data:/var/lib/grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 45s
      timeout: 15s
      retries: 5
      start_period: 90s

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    restart: always
    user: telegraf:984
    group_add:
      - "984"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./telegraf-container-conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
        - devices_network
    ports:
        - "9089:9273"
    depends_on:
        - prometheus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9273/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s  

  # iperf3:
  #   container_name: iperf3_server
  #   image: networkstatic/iperf3
  #   command: -s
  #   ports:
  #     - "5201:5201"
  #   networks:
  #     - devices_network

  simulated_device_1:
    container_name: ubuntu_device_1
    image: ubuntu_device
    build:
      dockerfile: ubuntu-dockerfile
      context: .
    restart: always
    hostname: device1
    cpus: "0.3"
    mem_limit: "256m"
    networks:
      - devices_network
    ports:
      - "9091:9273" # Expose Telegraf metrics endpoint
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9273/metrics"]
      interval: 20s
      timeout: 5s
      retries: 2

  simulated_device_2:
    container_name: ubuntu_device_2
    image: ubuntu_device
    build:
      dockerfile: ubuntu-dockerfile
      context: .
    restart: always
    hostname: device2
    cpus: "0.3"
    mem_limit: "512m"
    networks:
      - devices_network
    ports:
      - "9092:9273"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9273/metrics"]
      interval: 20s
      timeout: 5s
      retries: 2

  simulated_device_3:
    container_name: ubuntu_device_3
    image: ubuntu_device
    build:
      dockerfile: ubuntu-dockerfile
      context: .
    restart: always
    hostname: device3
    cpus: "0.4"
    mem_limit: "256m"
    networks:
      - devices_network
    ports:
      - "9093:9273"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9273/metrics"]
      interval: 20s
      timeout: 5s
      retries: 2
      
  simulated_device_4:
    container_name: alpine_device_4
    image: alpine_device
    build:
      dockerfile: alpine-dockerfile
      context: .
    restart: always
    hostname: device4
    cpus: "0.3"
    mem_limit: "256m"
    networks:
      - devices_network
    ports:
      - "9094:9273"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9273/metrics"]
      interval: 20s
      timeout: 5s
      retries: 2
      
  simulated_device_5:
    container_name: alpine_device_5
    image: alpine_device
    build:
      dockerfile: alpine-dockerfile
      context: .
    restart: always
    hostname: device5
    cpus: "0.3"
    mem_limit: "512m"
    networks:
      - devices_network
    ports:
      - "9095:9273"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9273/metrics"]
      interval: 20s
      timeout: 5s
      retries: 2


networks:
  devices_network:
    driver: bridge

volumes:
  grafana_data:
