groups:
  # Memory Alerts
  - name: memory_alerts
    interval: 10s
    rules:
      - alert: HighMemoryLoad
        expr: |
          100 * (
            memory_current{job=~".*", alias=~".*"} /
            on(alias, job) memory_total{job=~".*", alias=~".*"}
          ) >= 85
        for: 1m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "Memory load >= 85%"
          description: "Over the last 5 minutes, the average memory load was above 85% of the maximum memory available on {{ $labels.alias }}."

      - alert: FreeSwapMemoryLow
        expr: |
          100 * (
            memory_swap_free{job=~".*", alias=~".*"} /
            on(alias, job) memory_swap_total{job=~".*", alias=~".*"}
          ) <= 15
        for: 5m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "Memory Swap Free <= 15%"
          description: "Over the last 5 minutes, the average free swap memory was below 15% of the maximum swap available on {{ $labels.alias }}."

  # CPU Alerts
  - name: cpu_alerts
    interval: 60s
    rules:
      - alert: HighCPUUserLoad
        expr: cpu_user_load{job=~".*", alias=~".*"} >= 85
        for: 5m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "CPU User Load >= 85%"
          description: "Over the last 5 minutes, the average cpu load on {{ $labels.alias }}-{{ $labels.cpu }} was above 85%."

      - alert: HighCPUSystemLoad
        expr: cpu_system_load{job=~".*", alias=~".*"} >= 85
        for: 5m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "CPU System Load >= 85%"
          description: "Over the last 5 minutes, the average cpu load on {{ $labels.alias }}-{{ $labels.cpu }} was above 85%."

      - alert: HighCPUTotalLoad
        expr: |
          (100 - cpu_idle{job!="virtual_hosts", alias=~".*"}) >= 85
          or
          (absent(cpu_idle{job!="virtual_hosts", alias=~".*"}) and on() vector(85))
        for: 5m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "CPU Total Load >= 85%"
          description: "Over the last 5 minutes, the average cpu load on {{ $labels.alias }}-{{ $labels.cpu }} was above 85%."

  # Process Alerts
  - name: process_alerts
    interval: 60s
    rules:
      - alert: HighZombieProcessCount
        expr: processes_zombies{job=~".*", alias=~".*"} >= 10
        for: 5m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "Zombie Processes Count > 10"
          description: "Over the last 5 minutes, there were detected more than 10 zombie processes on {{ $labels.alias }}."

  # Disk Alerts
  - name: disk_alerts
    interval: 180s
    rules:
      - alert: LowPartitionSpace
        expr: |
          100 * (
            physical_disk_free{job="physical_host", alias=~".*", disk_partition=~".*"} /
            on(job, alias, disk_partition) (
              physical_disk_free{job="physical_host", alias=~".*", disk_partition=~".*"} +
              physical_disk_used{job="physical_host", alias=~".*", disk_partition=~".*"}
            )
          ) <= 15
        for: 20m
        labels:
          severity: critical
          team: sre
        annotations:
          summary: "Free Partition Space <= 15%"
          description: "Over the last hour, there has been 15% or less free space on {{ $labels.alias }}-{{ $labels.disk_partition }}."

      - alert: HighDiskIO
        expr: physical_diskio_io_util{job=~".*", alias=~".*", disk_partition=~".*"} >= 85
        for: 10m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "Disk I/O Load >= 85%"
          description: "Over the last 10 minutes, the disk i/o was above 85% on {{ $labels.alias }}-{{ $labels.disk_partition }}."

      # - alert: TestAlertPipeline
      #   expr: up{job="physical_host"} == 1  # Always true for running targets
      #   for: 10s
      #   labels:
      #     severity: info
      #     team: sre
      #   annotations:
      #     summary: "Test alert - pipeline verification"
      #     description: "This alert should always fire to test the alerting pipeline"