groups:
- name: diskio_normalization
  rules:
  - record: diskio_write
    expr: container_cgroup_io_stat_8:16_wbytes{job="virtual_hosts"}
    labels:
      disk_partition: "container"

  - record: diskio_read
    expr: container_cgroup_io_stat_8:16_rbytes{job="virtual_hosts"}
    labels:
      disk_partition: "container"

  - record: diskio_write
    expr: physical_diskio_write_bytes{job="physical_host"}

  - record: diskio_read
    expr: physical_diskio_read_bytes{job="physical_host"}

