groups:
- name: diskio_normalization
  rules:
  - record: container_wbytes_normalized
    expr: >
      label_replace(
          {__name__=~"container_cgroup_io_stat_.*_wbytes"},
        "disk_partition",
        "$1",
        "__name__",
        ".*io_stat_([0-9]+:[0-9]+)_wbytes"
      )

  - record: diskio_write
    expr: >
      irate(
        {__name__=~"container_wbytes_normalized|physical_diskio_write_bytes"}[10s]
        )
    labels:
      unit: "bytes/sec"

  - record: container_rbytes_normalized
    expr: >
      label_replace(
          {__name__=~"container_cgroup_io_stat_.*_rbytes"},
        "disk_partition",
        "$1",
        "__name__",
        ".*io_stat_([0-9]+:[0-9]+)_rbytes"
      )

  - record: diskio_read
    expr: >
      irate(
        {__name__=~"container_rbytes_normalized|physical_diskio_read_bytes"}[10s]
        )
    labels:
      unit: "bytes/sec"