groups:
  - name: memory_normalization
    rules:
      - record: memory_current
        expr: >
          label_replace(
            label_replace(
              container_cgroup_memory_current{job="virtual_hosts"},
              "instance", "", "", ""
            ),
            "path", "", "", ""
          )
        labels:
          unit: "bytes"

      - record: memory_current
        expr: >
          label_replace(
            label_replace(
              physical_mem_used{job="physical_host"},
              "instance", "", "", ""
            ),
            "path", "", "", ""
          )
        labels:
          unit: "bytes"

      - record: memory_total
        expr: >
          label_replace(
            label_replace(
              container_cgroup_memory_max{job="virtual_hosts"},
              "instance", "", "", ""
            ),
            "path", "", "", ""
          )
        labels:
          unit: "bytes"

      - record: memory_total
        expr: >
          label_replace(
            label_replace(
              physical_mem_total{job="physical_host"},
              "instance", "", "", ""
            ),
            "path", "", "", ""
          )
        labels:
          unit: "bytes"

      - record: memory_swap_total
        expr: >
          label_replace(
            label_replace(
              container_cgroup_memory_swap_max{job="virtual_hosts"},
              "instance", "", "", ""
            ),
            "path", "", "", ""
          )
        labels:
          unit: "bytes"

      - record: memory_swap_total
        expr: >
          label_replace(
            label_replace(
              physical_mem_swap_total{job="physical_host"},
              "instance", "", "", ""
            ),
            "path", "", "", ""
          )
        labels:
          unit: "bytes"

      - record: memory_swap_free
        expr: >
          label_replace(
            label_replace(
              (
                container_cgroup_memory_swap_max{job="virtual_hosts"}
                - container_cgroup_memory_swap_current{job="virtual_hosts"}
              ),
              "instance", "", "", ""
            ),
            "path", "", "", ""
          )
        labels:
          unit: "bytes"

      - record: memory_swap_free
        expr: >
          label_replace(
            label_replace(
              physical_mem_swap_free{job="physical_host"},
              "instance", "", "", ""
            ),
            "path", "", "", ""
          )
        labels:
          unit: "bytes"
