groups:
- name: network_normalization
  rules:
  - record: net_bytes_recv
    expr: |
      irate(
        {__name__=~"container_net_bytes_recv|physical_net_bytes_recv"}[30s]
        )
    labels:
      unit: "bytes/sec"

  - record: net_bytes_sent
    expr: |
      irate(
        {__name__=~"container_net_bytes_sent|physical_net_bytes_sent"}[30s]
        )
    labels:
      unit: "bytes/sec"

  - record: net_packets_recv
    expr: |
      irate(
        {__name__=~"container_net_packets_recv|physical_net_packets_recv"}[30s]
        )
    labels:
      unit: "packets/sec"

  - record: net_packets_sent
    expr: |
      irate(
        {__name__=~"container_net_packets_sent|physical_net_packets_sent"}[30s]
        )
    labels:
      unit: "packets/sec"

  - record: net_drop_in
    expr: |
      irate(
        {__name__=~"container_net_drop_in|physical_net_drop_in"}[30s]
        )
    labels:
      unit: "packets/sec"

  - record: net_drop_out
    expr: |
      irate(
        {__name__=~"container_net_drop_out|physical_net_drop_out"}[30s]
        )
    labels:
      unit: "packets/sec"

  - record: net_err_in
    expr: |
      irate(
        {__name__=~"container_net_err_in|physical_net_err_in"}[30s]
        )
    labels:
      unit: "packets/sec"

  - record: net_err_out
    expr: |
      irate(
        {__name__=~"container_net_err_out|physical_net_err_out"}[30s]
        )
    labels:
      unit: "packets/sec"