groups:
- name: network_normalization
  rules:
  - record: net_bytes_recv
    expr: |
      label_replace(
        container_net_bytes_recv{job="virtual_hosts"},
        "type", "virtual", "", ""
      )
    labels:
      unit: "bytes"

  - record: net_bytes_sent
    expr: |
      label_replace(
        container_net_bytes_sent{job="virtual_hosts"},
        "type", "virtual", "", ""
      )
    labels:
      unit: "bytes"

  - record: net_packets_recv
    expr: |
      label_replace(
        container_net_packets_recv{job="virtual_hosts"},
        "type", "virtual", "", ""
      )
    labels:
      unit: "packets"

  - record: net_packets_sent
    expr: |
      label_replace(
        container_net_packets_sent{job="virtual_hosts"},
        "type", "virtual", "", ""
      )
    labels:
      unit: "packets"

  - record: net_drop_in
    expr: |
      label_replace(
        container_net_drop_in{job="virtual_hosts"},
        "type", "virtual", "", ""
      )
    labels:
      unit: "packets"

  - record: net_drop_out
    expr: |
      label_replace(
        container_net_drop_out{job="virtual_hosts"},
        "type", "virtual", "", ""
      )
    labels:
      unit: "packets"

  - record: net_err_in
    expr: |
      label_replace(
        container_net_err_in{job="virtual_hosts"},
        "type", "virtual", "", ""
      )
    labels:
      unit: "packets"

  - record: net_err_out
    expr: |
      label_replace(
        container_net_err_out{job="virtual_hosts"},
        "type", "virtual", "", ""
      )
    labels:
      unit: "packets"

  - record: net_bytes_recv
    expr: |
      label_replace(
        physical_net_bytes_recv{job="physical_host"},
        "type", "physical", "", ""
      )
    labels:
      unit: "bytes"

  - record: net_bytes_sent
    expr: |
      label_replace(
        physical_net_bytes_sent{job="physical_host"},
        "type", "physical", "", ""
      )
    labels:
      unit: "bytes"

  - record: net_packets_recv
    expr: |
      label_replace(
        physical_net_packets_recv{job="physical_host"},
        "type", "physical", "", ""
      )
    labels:
      unit: "packets"

  - record: net_packets_sent
    expr: |
      label_replace(
        physical_net_packets_sent{job="physical_host"},
        "type", "physical", "", ""
      )
    labels:
      unit: "packets"

  - record: net_drop_in
    expr: |
      label_replace(
        physical_net_drop_in{job="physical_host"},
        "type", "physical", "", ""
      )
    labels:
      unit: "packets"

  - record: net_drop_out
    expr: |
      label_replace(
        physical_net_drop_out{job="physical_host"},
        "type", "physical", "", ""
      )
    labels:
      unit: "packets"

  - record: net_err_in
    expr: |
      label_replace(
        physical_net_err_in{job="physical_host"},
        "type", "physical", "", ""
      )
    labels:
      unit: "packets"

  - record: net_err_out
    expr: |
      label_replace(
        physical_net_err_out{job="physical_host"},
        "type", "physical", "", ""
      )
    labels:
      unit: "packets"
