groups:
- name: processes_normalization
  rules:
  - record: processes_total
    expr: |
      {__name__=~"container_processes_total|physical_processes_total", job=~"virtual_hosts|physical_host"}
    labels:
      unit: units

  - record: processes_running
    expr: |
      {__name__=~"container_processes_running|physical_processes_running", job=~"virtual_hosts|physical_host"}
    labels:
      unit: units

  - record: processes_sleeping
    expr: |
      {__name__=~"container_processes_sleeping|physical_processes_sleeping", job=~"virtual_hosts|physical_host"}
    labels:
      unit: units

  - record: processes_zombies
    expr: |
      {__name__=~"container_processes_zombies|physical_processes_zombies", job=~"virtual_hosts|physical_host"}
    labels:
      unit: units
      