apiVersion: 1
contactPoints:
  - orgId: 1
    name: SRE-Managers
    receivers:
      # - uid: telegram_receiver_1
      #   type: telegram
      #   disableResolveMessage: false
      #   settings:
      #     chatid: '"${GF_TELEGRAM_BOT_TOKEN}"'
      #     bottoken: '"${GF_TELEGRAM_CHAT_ID}"'
      #     message: |
      #       {{ template "telegram.message" . }}
      - uid: email_receiver_1
        type: email
        disableResolveMessage: false
        settings:
          addresses: "vcossetti@poli.ufrj.br"