apiVersion: 1
groups:
    - orgId: 1
      name: Memory Alerts
      folder: Monitoring
      interval: 10s
      rules:
        - uid: high-memory-load
          title: High Memory Load
          condition: Alarm Trigger
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                exemplar: false
                expr: |
                    100 * (
                      (memory_current{job=~".*", alias=~".*"})
                      /
                      on(alias, job)
                      (memory_max{job=~".*", alias=~".*"})
                    )
                format: time_series
                instant: false
                interval: ""
                intervalMs: 5000
                legendFormat: '{{alias}} {{name}}'
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: Avg Memory
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - Avg Memory
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: mean
                refId: Avg Memory
                type: reduce
            - refId: Alarm Trigger
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 10
                        type: gte
                      operator:
                        type: and
                      query:
                        params:
                            - Alarm Trigger
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: Avg Memory
                intervalMs: 1000
                maxDataPoints: 43200
                refId: Alarm Trigger
                type: threshold
          dashboardUid: bekb70hhnfh8ga
          panelId: 1
          noDataState: NoData
          execErrState: Error
          for: 20s
          annotations:
            __dashboardUid__: bekb70hhnfh8ga
            __panelId__: "1"
            description: Over the last 5 minutes, the average memory load was above 85% of the maximum memory.
            summary: Memory load >= 85%
          isPaused: false
          notification_settings:
            receiver: SRE-Managers

        - uid: high-swap-load
          title: High Memory Swap Load
          condition: Alarm Trigger
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                exemplar: false
                expr: |
                    100 * (
                      memory_swap_current{job=~".*", alias=~".*"}
                      /
                      on(alias, job)
                      memory_swap_max{job=~".*", alias=~".*"}
                    )
                format: time_series
                instant: false
                interval: ""
                intervalMs: 5000
                legendFormat: '{{alias}} {{name}}'
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: Avg Swap Load
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - Avg Swap Load
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: mean
                refId: Avg Swap Load
                type: reduce
            - refId: Alarm Trigger
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.2
                        type: gte
                      operator:
                        type: and
                      query:
                        params:
                            - Alarm Trigger
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: Avg Swap Load
                intervalMs: 1000
                maxDataPoints: 43200
                refId: Alarm Trigger
                type: threshold
          dashboardUid: bekb70hhnfh8ga
          panelId: 5
          noDataState: NoData
          execErrState: Error
          for: 20s
          annotations:
            __dashboardUid__: bekb70hhnfh8ga
            __panelId__: "5"
            description: Over the last 5 minutes, the average memory swap load was above 85% of the maximum swap memory.
            summary: Memory Swap Load >= 85%
          isPaused: false
          notification_settings:
            receiver: SRE-Managers
